version: '3'
services:
  proxy:
    build: ../proxy
    ports:
      - "443:443"
    environment:
      - CERTIFICATE_PASSWORD=dummyPass
      - PROXY_TO_URL=http://webapp:8081
    volumes:
      - ./volumes:/certificate-volume
  webapp:
    build: ./demo-web
    ports:
      - "8081:8081"
